# hash:sha256:2fdb4e067789cb15bbb2c7d7a625989f9bc456aa78b9931fff9ce001ce89a281
ARG REGISTRY_HOST
FROM $REGISTRY_HOST/codeocean/omix-r-visualization:r4.4.3-v2

ARG DEBIAN_FRONTEND=noninteractive
ARG GIT_ASKPASS
COPY git-ask-pass /
